---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Applied Statistics

Per [Wikipedia](https://en.wikipedia.org/wiki/Statistics), statistics is a branch of mathematics dealing with data collection, organization, analysis, interpretation and presentation. It is often using a sample of data to make inferences about a population. 

The goal of these mini-projects is to apply various statistical concepts to real-world data to answer questions through experimentation. 

## Files and Directory Structure

- __data__: All data is contained in the data folder or generated within the report. 

- The analysis including RMarkdown report and MD are provided above and linked below. 

## Analysis Questions

|  Question  | Description | Statistical Test(s) | Last Update
| :--------: | :---------: | ------------------- | -----------
| [Do NHL playoff teams have higher combined special teams performance compared to non-playoff teams?](https://github.com/bclark86/stats-fun/blob/master/nhl_playoffs_vs_specialteams/nhl_team_scoring_hypothesis_test.md) | Testing to see if there is a statistically significant difference in the mean combined special teams percentage for playoff-bound teams compared to non-playoff teams in 2018. | Simulated permutation test using R `infer` package | 2019-03-15
| [Does Brett Maher have a Hash Marks Problem?](http://htmlpreview.github.io/?https://github.com/bclark86/stats-fun/blob/master/nfl_hashmark_problem/nfl_hashmark_problem.html) | Testing to see if there is a statistically significant relationship between the hash mark of the attempt and the chances of a make for Brett Maher in 2018. | Simulated chi-square test using base R and the R `infer` package | 2019-08-14
